// Netlify runs this script before every deploy.
// It reads SHEETS_URL and SHEETS_SECRET from Netlify Environment Variables
// and writes js/config.js so the app can load them — without ever committing
// the real values to git.
const fs = require('fs');

const url    = process.env.SHEETS_URL    || '';
const secret = process.env.SHEETS_SECRET || '';

if (!url || !secret) {
  console.warn(
    '[build-config] WARNING: SHEETS_URL or SHEETS_SECRET env var is missing.\n' +
    '  Set them in Netlify Dashboard → Site settings → Environment variables.\n' +
    '  App will run in offline (localStorage-only) mode until they are set.'
  );
}

const content = `// Auto-generated by build-config.js — do not edit manually
const APP_CONFIG = {
  SHEETS_URL:    '${url}',
  SHEETS_SECRET: '${secret}'
};
`;

fs.writeFileSync('js/config.js', content, 'utf8');
console.log('[build-config] js/config.js written successfully.');
